### ISSUE TITLE
Put together failing test case for egui_virtual_list

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#38]
@lucasmerlin's egui_virtual_list seems to not support adding items to the start of a list in reverse chrononological order. when you scroll up it tends to skip:

https://cdn.jb55.com/s/virtual-list-buggy.mp4

Let's put together a minimal failing test case so that we can investigate this issue.

Alternatively we can look into @mikedilger's approach in gossip.

**Comment by lucasmerlin** [comment]
This is actually a problem I also had with egui_infinite_scroll (which also supports loading items from the top when scrolling up), and there is a fix for it (although not very pretty):
You can call `items_inserted_at_start` when you add items at the top, and it will measure the height of the inserted items and scroll be the measured amount to prevent it from jumping around. (This was actually a pain to implement because it's not something egui's ScrollArea supports on it's own, and scrolling a certain amount was buggy at that time)

You can also look at the both_directions example in the infinite scroll crate to see it implemented.

**Comment by jb55** [comment]
@lucasmerlin oops I just saw this comment. thanks! I will check out that code. it sounds like that's what we need.

**Comment by jb55** [comment]
@lucasmerlin I added the call right after I insert data into the list before render, I get this (starts at 5seconds):

https://cdn.jb55.com/s/bumpy.mp4

**Comment by jb55** [comment]
oh I may just need to turn off scroll animations... that makes sense

**Comment by lucasmerlin** [comment]
Yeah, the scroll animations are the problem. Are you using the latest egui version? You should be able to do ScrollArea::animated to turn them off.
Related egui stuff:
https://github.com/emilk/egui/pull/4309
https://github.com/emilk/egui/issues/4295

**Comment by jb55** [comment]
turning off animations fixed everything! this works great now. amazing. thanks!!
